import {Dimensions, StyleSheet} from 'react-native';
const {width} = Dimensions.get('window');


const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: 'white'},

  headerRow_r: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  header_r: {
    fontSize: 22,
    fontWeight: 'bold',
  },
  link_r: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#000',
    fontFamily: 'Source Serif 4',
  },
  ratingRow_r: {
    flexDirection:"row",
    alignItems: 'center',
    gap: 10,
    marginBottom: 15,
  },
  rating_r: {
    fontSize: 48,
    fontWeight: 'bold',
  },
  totalReviews_r: {
    fontWeight: 'bold',
    fontSize: 13,
    fontFamily: 'Source Serif 4',
  },
  card_r: {
    backgroundColor: '#ecfeff',
    padding: 15,
    borderBottomWidth: 1,
    borderColor: '#ccc',
    borderRadius: 4,
    marginBottom: 8,
  },
  cardHeader_r: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardTitle_r: {
    fontWeight: 'bold',
    fontSize: 15,
    fontFamily: 'Source Serif 4',
  },
  ratingText_r: {
    fontWeight: 'bold',
    color: '#22c55e',
  },
  message_r: {
    color: '#11A5D7',
    marginVertical: 5,
    fontWeight:"regular",
  },
  userInfo_r: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userText_r: {
    marginLeft: 4,
    fontWeight: 'bold',
    fontFamily: 'Source Serif 4',
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 5,
  },
  logo: {width: 80, height: 58},
  hero: {height: 400, marginBottom: 50},
  overlay: {
    flex: 1,
    // backgroundColor: 'rgba(0, 100, 0, 0.4)',
    justifyContent: 'center',
    paddingLeft: '10%',
  },
  subtitle: {
    color: '#fff',
    fontSize: 17,
    marginBottom: 10,
    fontFamily: 'Source Serif 4',
    fontWeight: 'bold',
  },
  title: {fontSize: 48, fontWeight: 'bold', marginBottom: 20},
  shopBtn: {
    borderRadius: 16,
    width: '30%',
    height: 40,
  },
  shopBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Source Serif 4',
    marginTop: 8,
  },
  scrollView: {paddingBottom: 20},
  cardWrapper_g: {
    width: width * 0.42,
    marginRight: 15,
    borderRadius: 20,
    backgroundColor: '#fff',
    overflow: 'hidden',
    shadowColor: 'rgba(0,0,0,0.5)', // shadow
    shadowRadius: 5,
    shadowOpacity: 0.3,
    shadowOffset: {width: 0, height: 2},
    elevation: 5,
    marginHorizontal: 15,
  },
  card_g: {
    backgroundColor: '#fff',
    borderRadius: 20,
  },
  imageBackground_g: {
    width: '100%',
    height: 200,
    resizeMode: 'stretch',
    justifyContent: 'flex-end',
  },
  gradientBox_g: {
    justifyContent: 'center',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    height: 50,
  },
  productName_g: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
    marginLeft: 10,
    fontFamily: 'Source Serif 4',
  },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 30,
    paddingHorizontal: 15,
    marginBottom: 0,
    height: 50,
    marginTop: 10,
    marginHorizontal: 10,
  },
  searchIcon: {marginRight: 10},
  micIcon: {marginLeft: 'auto'},
  textInput: {flex: 1, fontSize: 16},
  grid: {marginTop: 0},
  card: {
    flex: 1,
    padding: 90,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#000',
    marginHorizontal: 8,
  },
  imageIcon: {
    fontSize: 20,
    alignSelf: 'center',
  },
  cardTitle: {fontSize: 18, fontWeight: 'bold', marginBottom: 5},
  cardDesc: {fontSize: 14, color: 'grey'},
  tabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderBottomWidth: 1,
    paddingBottom: 10,
    marginTop: 10,
  },
  tabText: {
    fontWeight: 'bold',
    color: 'gray',
    fontSize: 15,
    fontFamily: 'Source Serif 4',
  },
  activeTabText: {color: 'black', borderBottomWidth: 2, borderColor: 'black'},
  productList: {padding: 10},
  productCard: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#000',
    margin: 5,
    padding: 10,
    borderRadius: 10,
  },
  productName: {
    fontWeight: 'semibold',
    fontSize: 14,
    fontFamily: 'Source Serif 4',
    marginBottom: 5,
  },
  productPrice: {fontSize: 14, color: 'gray', marginBottom: 8},
  seeMore: {
    textAlign: 'center',
    color: '#00AEEF',
    fontWeight: 'bold',
    marginVertical: 10,
    fontSize: 16,
  },
  header1: {flexDirection: 'row', alignItems: 'center', marginTop: 10},
  title1: {color: '#00AEEF', fontSize: 20, fontWeight: 'bold', flex: 1},
  arrow1: {color: '#00AEEF', fontSize: 22},
  productList1: {paddingVertical: 10},
  storage: {color: 'gray', marginBottom: 4},
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  quantityButton: {
    padding: 6,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#1C9C48',
    borderRadius: 4,
  },
  quantityBox: {
    width: 90,
    height: 32,
    marginHorizontal: 6,
    backgroundColor: '#1C9C48',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
  },
  quantityText: {fontSize: 18, color: '#1C9C48', fontWeight: 'semibold'},
  quantityNumber: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'semibold',
    fontFamily: 'Source Serif 4',
  },
  buyButton: {
    backgroundColor: '#00A94F',
    paddingVertical: 8,
    paddingHorizontal: 30,
    borderRadius: 4,
  },
  buyButtonText: {
    color: '#fff',
    textAlign: 'center',
    fontWeight: 'semibold',
    fontWeight: 'semibold',
    fontFamily: 'Source Serif 4',
  },
  searchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 30,
    margin: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 16,
    paddingLeft: 15,
    marginRight: 10,
    borderWidth: 2,
  },
  textInput_search: {
    flex: 1,
    paddingVertical: 10,
    color: ' #000',
    fontFamily: 'Source Serif 4',
    fontSize: 16,
  },
  icon: {
    padding: 10,
  },
  searchBtn: {
    padding: 10,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePlaceholder: {
    width: 160,
    height: 100,
    backgroundColor: '#eee',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#aaa',
  },
  phoneCard: {
    width: width,
    alignItems: 'center',
    justifyContent: 'center',
  },
  phoneImage: {
    width: '100%',
    height: 220,
  },
  offerList: {
    marginTop: 20,
    gap: 0,
  },
  offerCard: {
    width: width * 0.4,
    height: 173,
    borderRadius: 10,
    padding: 20,
    marginRight: 12,
    justifyContent: 'center',
    overflow: 'hidden', // ensure image respects borderRadius
  },
  offerImageBackground: {
    borderRadius: 10,
    resizeMode: 'cover',
    opacity: 0.9, // optional for slight dimming
  },
  offerTitle: {
    fontWeight: 'semibold',
    fontSize: 15,
    color: '#fff',
    marginBottom: 0,
    color: '#000',
    fontFamily: 'Source Serif 4',
    marginTop: 100,
  },
  offerSubtitle: {
    fontSize: 13,
    color: '#fff',
    fontWeight: 'regular',
    color: '#000',
  },
  greenButton: {
    backgroundColor: '#16a34a',
    borderRadius: 10,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 30,
  },
  greenButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  darkButton: {
    backgroundColor: '#1e1e1e',
    borderRadius: 10,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 15,
  },
  darkButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
});

const stylesSupport = StyleSheet.create({
  container: {
    // position: 'absolute',
    bottom: 30,
    right: 20,
    alignItems: 'flex-end',
    marginTop: 50,
  },
  menu: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 16,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  menuItem: {
    fontSize: 16,
    fontWeight: '600',
    marginVertical: 4,
    color: '#1e1e1e',
  },
  floatingButton: {
    backgroundColor: '#0ea5e9',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badge: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    backgroundColor: '#f97316',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  badgeText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
  },
});

export { styles, stylesSupport };