import {Dimensions, Platform, StyleSheet} from 'react-native';
const {width} = Dimensions.get('window');
const CARD_MARGIN = 16;
const cardWidth = (width - CARD_MARGIN * 3) / 2;

const styles = StyleSheet.create({
  listContainerD: {
    padding: 10,
  },
  cardD: {
    width: 200,
    backgroundColor: '#fff',
    borderRadius: 12,
    marginRight: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 4,
    elevation: 3,
  },
  cardM: {
    width: 200,
    backgroundColor: '#fff',
    borderRadius: 12,
    marginRight: 0,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 4,
    elevation: 3,
  },
  imageContainerD: {
    position: 'relative',
    backgroundColor: '#f4f4f4',
  },
  imageD: {
    width: '100%',
    height: 250,
    resizeMode: 'stretch',
  },
  imageM: {
    width: '90%',
    height: 200,
    resizeMode: 'stretch',
  },
  refurbishedLabelD: {
    position: 'absolute',
    alignSelf: 'center',
    fontSize: 12,
    color: '#000',
    backgroundColor: '#EAE6E5',
    width: '98%',
    textAlign: 'center',
    padding: 5,
  },
  heartIconD: {
    position: 'absolute',
    top: 25,
    right: 6,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 5,
    elevation: 2,
  },
  badge: {
    position: 'absolute',
    left: -8,
    top: 10,
    backgroundColor: '#FF3C3C',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  badgeTextD: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  gradeBoxD: {
    paddingVertical: 2,
    position: 'absolute',
    marginTop: 225,
    alignSelf: 'center',
    backgroundColor: '#fff',
    width: '92%',
    borderRadius: 10,
    borderWidth: 0.2,
  },
  gradeTextD: {
    fontSize: 12,
    fontWeight: '500',
    color: '#555',
    textAlign: 'center',
  },
  productNameD: {
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 6,
    marginHorizontal: 10,
    color: '#000',
  },
  colorTextD: {
    fontSize: 13,
    color: '#000',
    marginHorizontal: 10,
    marginTop: 2,
  },
  priceRowD: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 10,
    marginTop: 4,
    marginBottom: 10,
  },
  priceD: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
    marginRight: 6,
  },
  originalPriceD: {
    fontSize: 13,
    color: '#888',
    textDecorationLine: 'line-through',
  },
  leftContainer: {
    flex: 1,
    paddingRight: 10,
  },
  heading: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1A1A1A',
    marginBottom: 6,
  },
  subheading: {
    fontSize: 18,
    fontWeight: '500',
    color: '#333',
    marginBottom: 8,
  },
  description: {
    fontSize: 16,
    color: '#7E7E7E',
    marginBottom: 20,
  },
  button: {
    backgroundColor: '#EAE8E8',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignSelf: 'flex-start',
  },
  buttonText: {
    fontSize: 16,
    color: '#000',
    fontWeight: '600',
  },
  imageG: {
    width: width * 0.3,
    height: width * 0.3,
  },

  container: {flex: 1, backgroundColor: 'white'},

  swiper: {
    height: 220,
  },
  card_Top: {
    width: width - 15,
    marginHorizontal: 20,
    height: 200,
    borderRadius: 16,
    overflow: 'hidden',
    alignSelf: 'center',
  },
  image: {
    resizeMode: 'stretch',
    borderRadius: 16,
  },
  textContainer: {
    flex: 1,
  },
  titleT: {
    fontSize: 12,
    color: '#fff',
    marginTop: 5,
    width: '50%',
  },
  subtitleT: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
    marginBottom: 5,
    width: '40%',
  },

  dot: {
    backgroundColor: '#aaa',
    width: 6,
    height: 6,
    borderRadius: 3,
    margin: 3,
  },
  activeDot: {
    backgroundColor: '#fff',
    width: 8,
    height: 8,
    borderRadius: 4,
    margin: 3,
  },
  badge: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    backgroundColor: '#ff3e3e',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  badgeText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },

  headerRow_r: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  header_r: {
    fontSize: 22,
    fontWeight: 'bold',
  },
  link_r: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#000',
    fontFamily: 'Source Serif 4',
  },
  ratingRow_r: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 15,
  },
  rating_r: {
    fontSize: 48,
    fontWeight: 'bold',
  },
  totalReviews_r: {
    fontWeight: 'bold',
    fontSize: 13,
    fontFamily: 'Source Serif 4',
  },
  card_r: {
    backgroundColor: '#ecfeff',
    padding: 15,
    borderBottomWidth: 1,
    borderColor: '#ccc',
    borderRadius: 4,
    marginBottom: 8,
  },
  cardHeader_r: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardTitle_r: {
    fontWeight: 'bold',
    fontSize: 15,
    fontFamily: 'Source Serif 4',
  },
  ratingText_r: {
    fontWeight: 'bold',
    color: '#22c55e',
  },
  message_r: {
    color: '#11A5D7',
    marginVertical: 5,
    fontWeight: 'regular',
  },
  userInfo_r: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userText_r: {
    marginLeft: 4,
    fontWeight: 'bold',
    fontFamily: 'Source Serif 4',
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 5,
    backgroundColor: '#1C9C48',
  },
  logo: {width: 80, height: 58},
  hero: {height: 400, marginBottom: 50},
  overlay: {
    flex: 1,
    // backgroundColor: 'rgba(0, 100, 0, 0.4)',
    justifyContent: 'center',
    paddingLeft: '10%',
  },
  subtitle: {
    color: '#fff',
    fontSize: 17,
    marginBottom: 10,
    fontFamily: 'Source Serif 4',
    fontWeight: 'bold',
  },
  title: {fontSize: 48, fontWeight: 'bold', marginBottom: 20},
  shopBtn: {
    borderRadius: 16,
    width: '30%',
    height: 40,
  },
  shopBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Source Serif 4',
    marginTop: 8,
  },
  scrollView: {paddingBottom: 20},
  cardWrapper_g: {
    width: width * 0.42,
    marginRight: 15,
    borderRadius: 20,
    backgroundColor: '#fff',
    overflow: 'hidden',
    shadowColor: 'rgba(0,0,0,0.5)', // shadow
    shadowRadius: 5,
    shadowOpacity: 0.3,
    shadowOffset: {width: 0, height: 2},
    elevation: 5,
    marginHorizontal: 15,
  },
  card_g: {
    backgroundColor: '#fff',
    borderRadius: 20,
  },
  imageBackground_g: {
    width: '100%',
    height: 200,
    resizeMode: 'stretch',
    justifyContent: 'flex-end',
  },
  gradientBox_g: {
    justifyContent: 'center',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    height: 50,
  },
  productName_g: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
    marginLeft: 10,
    fontFamily: 'Source Serif 4',
  },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 30,
    paddingHorizontal: 15,
    marginBottom: 0,
    height: 50,
    marginTop: 10,
    marginHorizontal: 10,
  },
  searchIcon: {marginRight: 10},
  micIcon: {marginLeft: 'auto'},
  textInput: {flex: 1, fontSize: 16},
  grid: {marginTop: 0},
  card: {
    flex: 1,
    padding: 90,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#000',
    marginHorizontal: 8,
  },
  imageIcon: {
    fontSize: 20,
    alignSelf: 'center',
  },
  cardTitle: {fontSize: 18, fontWeight: 'bold', marginBottom: 5},
  cardDesc: {fontSize: 14, color: 'grey'},
  tabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderBottomWidth: 1,
    paddingBottom: 10,
    marginTop: 10,
  },
  tabText: {
    fontWeight: 'bold',
    color: 'gray',
    fontSize: 15,
    fontFamily: 'Source Serif 4',
  },
  activeTabText: {color: 'black', borderBottomWidth: 2, borderColor: 'black'},
  productList: {padding: 10},
  productCard: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#000',
    margin: 5,
    padding: 10,
    borderRadius: 10,
  },
  productName: {
    fontWeight: 'semibold',
    fontSize: 14,
    fontFamily: 'Source Serif 4',
    marginBottom: 5,
  },
  productPrice: {fontSize: 14, color: 'gray', marginBottom: 8},
  seeMore: {
    textAlign: 'center',
    color: '#00AEEF',
    fontWeight: 'bold',
    marginVertical: 10,
    fontSize: 16,
  },
  header1: {flexDirection: 'row', alignItems: 'center', marginTop: 10},
  title1: {color: '#00AEEF', fontSize: 20, fontWeight: 'bold', flex: 1},
  arrow1: {color: '#00AEEF', fontSize: 22},
  productList1: {paddingVertical: 10},
  storage: {color: 'gray', marginBottom: 4},
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  quantityButton: {
    padding: 5,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#1C9C48',
    borderRadius: 4,
  },
  quantityBox: {
    width: 80,
    height: 32,
    marginHorizontal: 6,
    backgroundColor: '#1C9C48',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
  },
  quantityText: {fontSize: 18, color: '#1C9C48', fontWeight: 'semibold'},
  quantityNumber: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'semibold',
    fontFamily: 'Source Serif 4',
  },
  buyButton: {
    backgroundColor: '#00A94F',
    paddingVertical: 8,
    paddingHorizontal: 30,
    borderRadius: 4,
  },
  buyButtonText: {
    color: '#fff',
    textAlign: 'center',
    fontWeight: 'semibold',
    fontWeight: 'semibold',
    fontFamily: 'Source Serif 4',
  },
  searchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 30,
    margin: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 16,
    paddingLeft: 15,
    marginRight: 10,
    borderWidth: 2,
  },
  textInput_search: {
    flex: 1,
    paddingVertical: 10,
    color: ' #000',
    fontFamily: 'Source Serif 4',
    fontSize: 16,
  },
  icon: {
    padding: 10,
  },
  searchBtn: {
    padding: 10,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePlaceholder: {
    width: 160,
    height: 100,
    backgroundColor: '#eee',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#aaa',
  },
  phoneCard: {
    width: width,
    alignItems: 'center',
    justifyContent: 'center',
  },
  phoneImage: {
    width: '100%',
    height: 220,
  },
  offerList: {
    marginTop: 10,
    gap: 0,
  },
  offerCard: {
    width: width * 0.4,
    height: 173,
    borderRadius: 10,
    padding: 20,
    marginRight: 12,
    justifyContent: 'center',
    overflow: 'hidden', // ensure image respects borderRadius
  },
  offerImageBackground: {
    borderRadius: 10,
    resizeMode: 'cover',
    opacity: 0.9, // optional for slight dimming
  },
  offerTitle: {
    fontWeight: 'semibold',
    fontSize: 15,
    color: '#fff',
    marginBottom: 0,
    color: '#000',
    fontFamily: 'Source Serif 4',
    marginTop: 100,
  },
  offerSubtitle: {
    fontSize: 13,
    color: '#fff',
    fontWeight: 'regular',
    color: '#000',
  },
  greenButton: {
    backgroundColor: '#16a34a',
    borderRadius: 10,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 30,
  },
  greenButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  darkButton: {
    backgroundColor: '#1e1e1e',
    borderRadius: 10,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 15,
  },
  darkButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  timerWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginHorizontal: 10,
  },
  timeContainer: {
    alignItems: 'center',
  },
  timeBox: {
    backgroundColor: '#E6F5EA',
    paddingVertical: 20,
    paddingHorizontal: 25,
    borderRadius: 12,
    marginBottom: 5,
  },
  timeValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#000',
  },
  timeLabel: {
    fontSize: 14,
    color: '#000',
    fontWeight: '500',
  },
  card_bulk: {
    width: width,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardContent_bulk: {
    backgroundColor: '#eee',
    borderRadius: 16,
    padding: 20,
    flex: 1,
    marginRight: 10,
  },
  tag_bulk: {
    fontSize: 13,
    color: '#666',
    marginBottom: 5,
  },
  title_bulk: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#111',
    marginBottom: 4,
  },
  subtitle_bulk: {
    fontSize: 14,
    color: '#444',
  },
  iconBtn_bulk: {
    width: 50,
    height: 50,
    backgroundColor: '#222',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dotsContainer_bulk: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
  },
  dot_bulk: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#00AEEF',
    marginHorizontal: 5,
  },
  activeDot_bulk: {
    backgroundColor: '#00AEEF',
  },

  cardDO: {
    width: width * 0.9,
    backgroundColor: '#fff',
    borderRadius: 16,
    alignSelf: 'center',
    marginVertical: 10,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.12,
        shadowRadius: 8,
        borderWidth: 0.2,
      },
      android: {
        elevation: 4,
      },
    }),
  },

  imageDO: {
    width: '100%',
    height: 180,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  contentDO: {
    padding: 16,
  },
  titleDO: {
    fontSize: 20,
    fontWeight: '600',
    color: '#222',
    marginBottom: 6,
  },
  subtitleDO: {
    fontSize: 15,
    color: '#666',
    marginBottom: 20,
    lineHeight: 22,
  },
  buttonDO: {
    backgroundColor: '#03A9F4',
    borderRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignSelf: 'flex-start',
    ...Platform.select({
      ios: {
        shadowColor: '#03A9F4',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.2,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  buttonTextDO: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },

  gridSD: {
    paddingHorizontal: CARD_MARGIN,
    paddingTop: 20,
    paddingBottom: 0,
  },
  rowSD: {
    justifyContent: 'space-between',
    marginBottom: CARD_MARGIN,
  },
  cardSD: {
    width: cardWidth,
    backgroundColor: '#F3F3F3',
    borderRadius: 16,
    padding: 16,
    marginTop: 0,
  },
  iconCircleSD: {
    backgroundColor: '#23A455',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  cardTitleSD: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111',
    marginBottom: 6,
  },
  cardDescriptionSD: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },

  containerSUPPORT_CARDS: {
    paddingHorizontal: 0,
    paddingTop: 12,
    paddingBottom: 24,
  },
  cardSUPPORT_CARDS: {
    backgroundColor: '#ECE9E8', // soft gray from screenshot
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  iconCircleSUPPORT_CARDS: {
    backgroundColor: '#23A455',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  cardTitleSUPPORT_CARDS: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111',
    marginBottom: 6,
  },
  cardDescriptionSUPPORT_CARDS: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },

  categoryCard: {
    alignItems: 'center',
    marginRight: 12,
    marginHorizontal: 15,
    marginTop:10,
  },
  categoryImage: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
  },
  categoryText: {
    marginTop: 6,
    fontSize: 12,
    color: '#222',
  },
  banner: {
    width: '100%',
    height: 200,
    justifyContent: 'flex-end',
  },
  bannerOverlay: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  bannerText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
  },
});

const stylesSupport = StyleSheet.create({
  container: {
    // position: 'absolute',
    bottom: 30,
    right: 20,
    alignItems: 'flex-end',
    marginTop: 50,
  },
  menu: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 16,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  menuItem: {
    fontSize: 16,
    fontWeight: '600',
    marginVertical: 4,
    color: '#1e1e1e',
  },
  floatingButton: {
    backgroundColor: '#0ea5e9',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badge: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    backgroundColor: '#f97316',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  badgeText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
  },
});

export {styles, stylesSupport};
