import {StyleSheet} from 'react-native';

const styles_forgetotp = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F1FFFA',
  },
  backButton: {
    marginTop: 20,
    marginLeft: 20,
    width: 40,
    height: 40,
    backgroundColor: '#F1FFFA',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#1A1A2D',
    textAlign: 'center',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: '#555',
    marginBottom: 30,
    textAlign: 'center',
    fontFamily: 'Source Serif 4',
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  otpBox: {
    width: 70,
    height: 70,
    borderWidth: 1,
    borderColor: '#1A1A2D',
    borderRadius: 12,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: 'bold',
    marginHorizontal: 10,
    backgroundColor: '#F1FFFA',
    color: '#111',
  },
  button: {
    backgroundColor: '#478F4E',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  buttonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
    fontFamily: 'Source Serif 4',
  },
  resendText: {
    fontSize: 16,
    color: '#666666',
    fontWeight: 'semibold',
  },
  errorText: {
    color: 'red',
    fontSize: 14,
    marginBottom: 10,
    marginLeft: 5,
    fontFamily: 'Source Serif 4',
  },
});

const styles_forgetpassword = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F1FFFA', // very light green like screenshot
  },
  backButton: {
    marginTop: 20,
    marginLeft: 20,
    width: 40,
    height: 40,
    backgroundColor: '#F1FFFA',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    alignItems: 'stretch',
    marginTop: 20,
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#111',
    marginBottom: 10,
  },
  description: {
    fontSize: 16,
    color: '#555',
    marginBottom: 30,
    fontWeight: 'regular',
    fontFamily: 'Source Serif 4',
  },
  label: {
    fontSize: 14,
    fontWeight: 'regular',
    marginBottom: 8,
    color: '#1A1A2D',
  },
  input: {
    height: 50,
    borderColor: '#333333',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 16,
    marginBottom: 25,
    backgroundColor: '#F1FFFA',
    fontSize: 16,
  },
  button: {
    backgroundColor: '#478F4E', // green button
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 25,
  },
  buttonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
    fontFamily: 'Source Serif 4',
  },
  footer: {
    textAlign: 'center',
    fontSize: 14,
    color: '#666666',
    fontWeight: 'regular',
    fontFamily: 'Source Serif 4',
  },
  loginLink: {
    fontWeight: 'semibold',
    color: '#1A1A2D',
    fontSize: 14,
    fontFamily: 'Source Serif 4',
  },
  errorText: {
    color: 'red',
    fontSize: 14,
    marginBottom: 10,
    marginLeft: 5,
    fontFamily: 'Source Serif 4',
  },
});

const styles_setpassword = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F1FFFA',
  },
  backButton: {
    marginTop: 20,
    marginLeft: 20,
    width: 40,
    height: 40,
    backgroundColor: '#F1FFFA',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#1A1A2D',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#666666',
    marginBottom: 30,
    fontWeight: 'regular',
    fontFamily: 'Source Serif 4',
  },
  label: {
    fontSize: 14,
    fontWeight: 'regular',
    color: '#1A1A2D',
    marginBottom: 6,
    fontWeight: 'regular',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#333333',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    backgroundColor: '#F1FFFA',
    height: 52,
    marginBottom: 20,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  button: {
    backgroundColor: '#478F4E',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 30,
  },
  buttonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
    fontFamily: 'Source Serif 4',
  },
  footer: {
    textAlign: 'center',
    fontSize: 16,
    color: '#666',
  },
  loginLink: {
    fontWeight: 'semibold',
    color: '#000',
    fontSize: 16,
  },
  errorText: {
    color: 'red',
    fontSize: 14,
    marginBottom: 10,
    marginLeft: 5,
    fontFamily: 'Source Serif 4',
  },
});

export {styles_forgetotp, styles_forgetpassword, styles_setpassword};
